import PDFDocument from "pdfkit";
import PurchaseOrder, { PO_STATUS } from "../Schema/PurchaseOrder.js";
import { nextReference } from "./referenceService.js";

/**
 * Create a PO from an approved quotation. Money is a frozen paise snapshot from
 * quotation.computed; never recomputed. Idempotent per quotation.
 */
export async function generatePurchaseOrder({ tenantId, rfq, quotation, issuedBy }) {
  const existing = await PurchaseOrder.findOne({
    tenantId,
    quotationId: quotation._id,
    status: { $ne: PO_STATUS.CANCELLED },
  });
  if (existing) return existing;

  const number = await nextReference(tenantId, "purchaseOrder");
  const c = quotation.computed || {};
  const items = (quotation.items || [])
    .filter((it) => it.unitPrice !== null && it.unitPrice !== undefined)
    .map((it) => ({
      name: it.name,
      qty: it.qty,
      unit: it.unit,
      unitPrice: it.unitPrice,
      lineTotal: it.lineTotal,
    }));

  return PurchaseOrder.create({
    tenantId,
    number,
    rfqId: rfq._id,
    quotationId: quotation._id,
    vendorId: quotation.vendorId,
    currency: quotation.currency || "INR",
    items,
    subtotal: c.subtotal || 0,
    taxTotal: c.taxTotal || 0,
    discountTotal: c.discountTotal || 0,
    grandTotal: c.grandTotal || 0,
    status: PO_STATUS.ISSUED,
    issuedBy,
    expectedDelivery: quotation.terms?.deliveryDate || null,
    notes: `Auto-generated on approval of quotation ${quotation._id}.`,
  });
}

function money(paise, currency) {
  if (paise == null || !Number.isFinite(Number(paise))) return "\u2014";
  return `${(Number(paise) / 100).toFixed(2)} ${currency}`;
}

export function buildPoPdfBuffer(po, { rfq = {}, vendor = {} } = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks = [];
      doc.on("data", (c) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const currency = po.currency || "INR";
      const right = doc.page.width - 50;
      const cols = { name: 50, qty: 300, unit: 350, price: 410, total: 490 };

      doc.fontSize(20).fillColor("black").text("PURCHASE ORDER", { align: "right" });
      doc.fontSize(10).fillColor("#444").text(po.number, { align: "right" });
      doc.moveDown(1);
      doc.fillColor("black").fontSize(11).text(`RFQ: ${rfq.reference || po.rfqId}`);
      doc.text(`Vendor: ${vendor.name || po.vendorId}`);
      doc.text(`Issued: ${new Date(po.issuedAt || Date.now()).toISOString().slice(0, 10)}`);
      if (po.expectedDelivery)
        doc.text(`Expected delivery: ${new Date(po.expectedDelivery).toISOString().slice(0, 10)}`);
      doc.text(`Status: ${po.status}`);
      doc.moveDown(0.6);
      doc.strokeColor("#ccc").moveTo(50, doc.y).lineTo(right, doc.y).stroke();
      doc.moveDown(0.5);

      const y0 = doc.y;
      doc.fontSize(9).font("Helvetica-Bold");
      doc.text("Item", cols.name, y0, { width: cols.qty - cols.name });
      doc.text("Qty", cols.qty, y0, { width: cols.unit - cols.qty });
      doc.text("Unit", cols.unit, y0, { width: cols.price - cols.unit });
      doc.text("Unit Price", cols.price, y0, { width: cols.total - cols.price, align: "right" });
      doc.text("Total", cols.total, y0, { width: right - cols.total, align: "right" });
      doc.font("Helvetica");
      doc.moveDown(0.8);

      for (const it of po.items || []) {
        const y = doc.y;
        doc.fontSize(9);
        doc.text(String(it.name), cols.name, y, { width: cols.qty - cols.name - 4, ellipsis: true });
        doc.text(String(it.qty), cols.qty, y, { width: cols.unit - cols.qty - 4 });
        doc.text(String(it.unit || ""), cols.unit, y, { width: cols.price - cols.unit - 4 });
        doc.text(money(it.unitPrice, currency), cols.price, y, { width: cols.total - cols.price - 4, align: "right" });
        doc.text(money(it.lineTotal, currency), cols.total, y, { width: right - cols.total, align: "right" });
        doc.moveDown(0.6);
      }

      doc.moveDown(0.4);
      doc.strokeColor("#ccc").moveTo(50, doc.y).lineTo(right, doc.y).stroke();
      doc.moveDown(0.4);
      const totalRow = (label, paise, bold) => {
        const y = doc.y;
        if (bold) doc.font("Helvetica-Bold");
        doc.fontSize(10).text(label, cols.price - 60, y, { width: cols.total - (cols.price - 60) - 4, align: "right" });
        doc.text(money(paise, currency), cols.total, y, { width: right - cols.total, align: "right" });
        doc.font("Helvetica");
        doc.moveDown(0.3);
      };
      totalRow("Subtotal", po.subtotal);
      totalRow("Discount", po.discountTotal);
      totalRow("Tax", po.taxTotal);
      totalRow("Grand Total", po.grandTotal, true);

      doc.moveDown(1.5);
      doc.fontSize(8).fillColor("#888").text(
        "Auto-generated by VendorBridge on quotation approval.",
        50,
        doc.page.height - 60,
        { width: right - 50, align: "center" }
      );
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function streamPoPdf(res, po, opts = {}) {
  const buffer = await buildPoPdfBuffer(po, opts);
  const safe = String(po.number || "po").replace(/[^A-Za-z0-9._-]/g, "_");
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${safe}.pdf"`);
  res.setHeader("Content-Length", buffer.length);
  res.end(buffer);
}

export default { generatePurchaseOrder, buildPoPdfBuffer, streamPoPdf };
